TEXTS = {
    'comm': ['Привет! Я - Sentex-бот. Для начала выберите уровень сложности.',
             'Отлично! Правила: смотрите на слова - составляете предложение на английском. Если непонятно: '
             'нажимаете на слова - появляется подсказка. Чтобы прервать упражнение, напишите «стоп». Набираете 10 '
             'баллов и упражнение заканчивается. Напишите что-нибудь, чтобы продолжить',
             'Составьте предложение из данных слов.', 'Выберите тему.',
             'Начинаем упражнение на тему emphatic constructions. Напишите что-нибудь, чтобы продолжить.',
             'Начинаем упражнение на тему All Tenses. Напишите что-нибудь, чтобы продолжить.',
             'Начинаем упражнение на тему Present Simple.  Напишите что-нибудь, чтобы продолжить.',
             'Начинаем упражнение на тему Past Simple. Основные конструкции:\nвторая форма глагола.\n'
             'Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Passive Voice. Основные конструкции:\nbe с 3-й формой глагола.\n'
             ' Напишите что-нибудь, чтобы продолжить',
             'Упражнение на тему Modal Verbs: Advice. Основные конструкции:\nMaybe you should\nought to\n'
             'Why don\'t you\nНапишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Present Perfect vs Past Simple. Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Present Perfect Continuous. Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Present Perfect Continuous vs Past Simple. '
             'Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Present Contunuous. Основные конструкции: be + Ving. '
             'Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему There is/ There are. Примеры:\nНа столе есть несколько яблок ---> '
             'There are a few apples on the table\nНа столе нет никаких яблок ---> There are not any apples on the '
             'table\nНа столе есть какие-нибудь яблоки? ---> Are there any apples on the table?\n'
             'Напишите что-нибудь, чтобы продолжить',
             'Начинаем упражнение на тему Going to. Примеры:\nЯ собираюсь выучить английский ---> '
             'I am going to learn English\nОн не собирается ехать на работу ---> He is not going to go to work\n'
             'Собираешься ли ты посмотреть фильм? ---> Are you going to watch a film?'],
    'error': ['Что-то пошло не так. Начните сначала с помощью /start', 'Напишите "стоп" или начните сначала'],
    'start_handler':
        ['Elementary', 'Pre-Intermediate', 'Intermediate', 'Advanced'],
    'el_select': ['Present Simple', 'Past Simple', 'Present Continuous', 'There is/are', 'Going to'],
    'el': {
        'pres_simple': ['I work here',
                        'I do not work here',
                        'Do you work here?',
                        'You work',
                        'You do not work',
                        'He works',
                        'He does not work',
                        'Does he work here?',
                        'She works',
                        'She does not work',
                        'Does she work here?',
                        'We work',
                        'We do not work',
                        'Do we work here?',
                        'They work',
                        'They do not work',
                        'Do they work here?',
                        'I play poker',
                        'I do not play poker',
                        'Do you play poker?',
                        'You play poker',
                        'You do not play poker',
                        'He plays poker',
                        'He does not play poker',
                        'Does he play poker?',
                        'She plays poker',
                        'She does not play poker',
                        'Does she play poker?',
                        'We play poker',
                        'We do not play poker',
                        'They play poker',
                        'They do not play poker',
                        'Do they play poker?',
                        'I sleep 7 hours every day',
                        'I do not sleep 7 hours every day',
                        'Do you sleep 7 hours every day?',
                        'How much do you sleep every day?',
                        'You sleep 7 hours every day',
                        'You do not sleep 7 hours every day',
                        'He sleeps 7 hours every day',
                        'He does not sleep 7 hours every day',
                        'Does he sleep 7 hours every day?',
                        'How much does he sleep every day?',
                        'She sleeps 7 hours every day',
                        'She does not sleep 7 hours every day',
                        'Does she sleep 7 hours every day?',
                        'How much does she sleep every day?',
                        'We sleep 7 hours every day',
                        'We do not sleep 7 hours every day',
                        'Do we sleep 7 hours every day?',
                        'How much do we sleep every day?',
                        'They sleep 7 hours every day',
                        'They do not sleep 7 hours every day',
                        'Do they sleep 7 hours every day?',
                        'How much do they sleep every day?',
                        'I eat soup',
                        'I do not eat bread',
                        'You eat pizza',
                        'You do not eat pasta',
                        'Do you eat burgers?',
                        'What do you eat?',
                        'He eats sushi',
                        'He does not eat burgers',
                        'Does he eat burgers?',
                        'What does he eat?',
                        'She eats oatmeal',
                        'She does not eat pizza',
                        'Does she eat meat?',
                        'What does she eat?',
                        'We eat meat',
                        'We do not eat meat',
                        'They eat fast food',
                        'They do not eat soup',
                        'Do they eat pasta?',
                        'What do they eat?',
                        'I think',
                        'I do not think',
                        'You think',
                        'You do not think',
                        'What do you think about?',
                        'He thinks',
                        'He does not think',
                        'What does he think about?',
                        'She thinks',
                        'She does not think',
                        'What does she think about?',
                        'We think',
                        'We do not think',
                        'They think',
                        'They do not think',
                        'What do they think about?',
                        'I speak English well',
                        'I do not speak English well',
                        'You speak English well',
                        'You do not speak English well',
                        'Do you speak English well?',
                        'He speaks English well',
                        'He does not speak English well',
                        'Doe he speak English well?',
                        'She speaks English well',
                        'She does not speak English well',
                        'Does she speak English well?',
                        'We speak English well',
                        'We do not speak English well',
                        'They speak English well',
                        'They do not speak English well',
                        'Do they speak English well?',
                        'I read a book every day',
                        'I do not read a book every day',
                        'You read a book',
                        'You do not read a book',
                        'How often do you read books?',
                        'He sometimes reads books',
                        'He does not usually read books',
                        'How often does he read books?',
                        'She never reads books',
                        'She does not read books',
                        'How often does she read books?',
                        'We read a lot of books',
                        'We do not read a lot of books',
                        'They seldom read books',
                        'They do not usually read books',
                        'How often do they read books?',
                        'I look at the clock',
                        'I do not look at the clock',
                        'You look at the clock',
                        'You do not look at the clock',
                        'He looks at the clock',
                        'He does not look at the clock',
                        'She looks at the clock',
                        'She does not look at the clock',
                        'We look at the clock',
                        'We do not look at the clock',
                        'They look at the clock',
                        'They do not look at the clock',
                        'I go to work',
                        'I do not go to work',
                        'You go to work',
                        'You do not go to work',
                        'He goes to work',
                        'He does not go to work',
                        'She goes to work',
                        'She does not go to work',
                        'We go to work',
                        'We do not go to work',
                        'They go to work',
                        'They do not go to work',
                        'I eat breakfast',
                        'I do not eat breakfast',
                        'You eat breakfast',
                        'You do not eat breakfast',
                        'Do you eat breakfast?',
                        'He eats breakfast',
                        'He does not eat breakfast',
                        'Does he eat breakfast?',
                        'She eats breakfast',
                        'She does not eat breakfast',
                        'Does she eat breakfast?',
                        'We eat breakfast',
                        'We do not eat breakfast',
                        'They eat breakfast',
                        'They do not eat breakfast',
                        'Do they eat breakfast?',
                        'I eat lunch',
                        'I do not eat lunch',
                        'You eat lunch',
                        'You do not eat lunch',
                        'He eats lunch',
                        'He does not eat lunch',
                        'She eats lunch',
                        'She does not eat lunch',
                        'We eat lunch',
                        'We do not eat lunch',
                        'They eat lunch',
                        'They do not eat lunch',
                        'I eat dinner',
                        'I do not eat dinner',
                        'You eat dinner',
                        'You do not eat dinner',
                        'He eats dinner',
                        'He does not eat dinner',
                        'She eats dinner',
                        'She does not eat dinner',
                        'We eat dinner',
                        'We do not eat dinner',
                        'They eat dinner',
                        'They do not eat dinner',
                        'I listen to music',
                        'I do not listen to music',
                        'You listen to music',
                        'You do not listen to music',
                        'Do you listen to music?',
                        'What music do you listen to?',
                        'He listens to music',
                        'He does not listen to music',
                        'Does he listen to music?',
                        'What music does he listen to?',
                        'She listens to music',
                        'She does not listen to music',
                        'Does she listen to music?',
                        'What music does she listen to?',
                        'We listen to music',
                        'We do not listen to music',
                        'They listen to music',
                        'They do not listen to music',
                        'Do they listen to music?',
                        'What music do they listen to?',
                        'I play the guitar',
                        'I do not play the guitar',
                        'You play the guitar',
                        'You do not play the guitar',
                        'Do you play the guitar?',
                        'He plays the guitar',
                        'He does not play the guitar',
                        'Does he play the guitar?',
                        'She plays the guitar',
                        'She does not play the guitar',
                        'Does she play the guitar?',
                        'We play the guitar',
                        'We do not play the guitar',
                        'They play the guitar',
                        'They do not play the guitar',
                        'Do they play the guitar?',
                        'I write a lot of emails every day',
                        'I do not write an email',
                        'You write an email',
                        'You do not write an email',
                        'He writes an email',
                        'He does not write an email',
                        'She writes an email',
                        'She does not write an email',
                        'We write an email',
                        'We do not write an email',
                        'They write an email',
                        'They do not write an email',
                        'I say hello',
                        'I do not say hello',
                        'You say hello',
                        'You do not say hello',
                        'He says hello',
                        'He does not say hello',
                        'She says hello',
                        'She does not say hello',
                        'We say hello',
                        'We do not say hello',
                        'They say hello',
                        'They do not say hello',
                        'I put flowers on the table',
                        'I do not put flowers on the table',
                        'You put flowers on the table',
                        'You do not put flowers on the table',
                        'He puts flowers on the table',
                        'He does not put flowers on the table',
                        'She puts flowers on the table',
                        'She does not put flowers on the table',
                        'We put flowers on the table',
                        'We do not put flowers on the table',
                        'They put flowers on the table',
                        'They do not put flowers on the table',
                        'I close the door',
                        'I do not close the door',
                        'You close the door',
                        'You do not close the door',
                        'He closes the door',
                        'He does not close the door',
                        'She closes the door',
                        'She does not close the door',
                        'We close the door',
                        'We do not close the door',
                        'They close the door',
                        'They do not close the door',
                        'I talk with my friend',
                        'I do not talk with my friend',
                        'You talk with my friend',
                        'You do not talk with my friend',
                        'He talks with my friend',
                        'He does not talk with my friend',
                        'She talks with my friend',
                        'She does not talk with my friend',
                        'We talk with my friend',
                        'We do not talk with my friend',
                        'They talk with my friend',
                        'They do not talk with my friend',
                        'I talk with my boss',
                        'I do not talk with my boss',
                        'You talk to your boss',
                        'You do not talk to your boss',
                        'Do you talk with your boss?',
                        'He talks with his boss',
                        'He does not talk with his boss',
                        'Does he talk with his boss?',
                        'She talks with his boss',
                        'She does not talk with his boss',
                        'Does she talk with her boss?',
                        'We talk with our boss',
                        'We do not talk with our boss',
                        'They talk with their boss',
                        'They do not talk with their boss',
                        'Do they talk with their boss?',
                        'I am sixteen years old.',
                        'Juana cooks dinner for her family',
                        'They eat lunch at 12:00',
                        'Nina takes medicine when she is sick',
                        'I like chocolate',
                        'He drives a nice car',
                        'We want to see a movie tonight',
                        'They study English at school',
                        'I want to go home now',
                        'We eat pasta once a week',
                        'It snows here in December'],
        'past_simple': [
            'I studied English yesterday',
            'I did not drink any beer last night',
            'What time did he get up yesterday?',
            'We woke up very late yesterday',
            'What did he give his mother for Christmas?',
            'We did not use the computer last night',
            'Did she make good coffee?',
            'They lived in Paris',
            'I lived in Barcelona when I was a child',
            'She read the newspaper yesterday',
            'I did not watch TV on Saturday',
            'We did not go to the cinema on Monday',
            'What did you do on Monday?',
            'He did not study for the exam',
            'I studied for exam at the weekends',
            'Did you study for the exam?',
            'I called my friend last week',
            'They did not call me yesterday',
            'Did he call you?',
            'Did I forget something?',
            'I think I forgot something',
            'What time did the film start?',
            'I came to the party',
            'I did not come to the party',
            'Did you come to the party?',
            'I was scared to watch this film',
            'He broke a vase',
            'We did not break a vase',
            'Did you break a vase?',
            'The teacher began a class',
            'The teacher did not begin a class',
            'When did the teacher begin a class?',
            'We built this house in 1990',
            'When did you build this house?',
            'I brought beer and wine to the party',
            'He did not bring anything to the party',
            'What did you bring to the party?',
            'Did you bring the cake to the party?',
            'I bought a new car last week',
            'He did not buy a new car last week',
            'What did you buy last year?',
            'We caught a big fish at the weekend',
            'Did you catch anything?',
            'She drank a glass of champagne last night',
            'She did not drink a glass of champagne last night',
            'What did you drink last night?',
            'Did you drink anything last night?',
            'He ate a sandwich for breakfast',
            'I did not eat a sandwich for breakfast',
            'What did you eat for breakfast?',
            'Did you eat a sandwich for breakfast today?',
            'He found the keys to his house',
            'He did not find the keys to his house',
            'Did he find the keys to his house?',
            'What did they find?',
            'We flew to Greece last summer',
            'They did not fly to Spain last year',
            'Where did you fly last month?',
            'Did she fly to Russia last week?',
            'The teacher gave her homework',
            'I did not give them a present',
            'What did she give you?',
            'I went to school 20 years ago',
            'He did not go to a kindergarten',
            'Where did you go on your last vacation?',
            'She had a house in the countryside 2 years ago',
            'I did not have a house in the countryside',
            'Did you have a car 10 years ago?',
            'I left my keys in the car',
            'He did not leave his keys in the car',
            'Did you leave your keys in the car?',
            'He made a mistake',
            'We made a mistake',
            'She did not make a mistake',
            'They did not make a mistake',
            'Did you make a mistake?',
            'I paid the rent last week',
            'He did not pay his rent last week',
            'Did she pay her rent last week?',
            'I put the money in the wallet',
            'He did not put flowers in a vase',
            'Did she put the money in the wallet?',
            'What did he put in the wallet?',
            'She read 10 books last month',
            'I did not read any books last week',
            'What did you read last month?',
            'Did he read this book?',
            'He said hello',
            'She did not say hello',
            'What did they say?',
            'I saw an interesting article in a magazine',
            'We did not see an interesting article in a magazine',
            'What did you see?',
            'I spoke about a promotion with my boss',
            'He did not speak about a promotion with his boss',
            'What did she speak about with her boss?',
            'He wrote 5 emails yesterday',
            'What did you write?',
            'You did not write emails yesterday'
        ],
        'pres_cont': [
            'I am listening to music now',
            'I am not listening to music now',
            'You are listening to music now',
            'You are not listening to music now',
            'He is listening to music now',
            'He is not listening to music now',
            'She is listening to music now',
            'She is not listening to music now',
            'We are listening to music now',
            'We are not listening to music now',
            'They are listening to music now',
            'They are not listening to music now',
            'Are you listening to music now?',
            'Is he listening to music now?',
            'Are they listening to music now?',
            'What are you listening now?',
            'What is he doing now?',
            'What is she doing now?',
            'What are they doing now?',
            'I am watching tv at the moment',
            'I am not watching tv at the moment',
            'You are watching tv at the moment',
            'You are not watching tv at the moment',
            'He is watching tv at the moment',
            'He is not watching tv at the moment',
            'She is watching tv at the moment',
            'She is not watching tv at the moment',
            'We are watching tv at the moment',
            'We are not watching tv at the moment',
            'They are watching tv at the moment',
            'They are not watching tv at the moment',
            'Is he watching tv at the moment?',
            'Is she watching tv at the moment?',
            'Are they watching tv at the moment?',
            'I am wearing a jacket now',
            'I am not wearing a jacket now',
            'What are you wearing?',
            'You are wearing jeans now',
            'You are not wearing trousers now'
            'He is wearing a t-shirt now',
            'He is not wearing a shirt now',
            'What is he wearing now?',
            'She is wearing trousers now',
            'She is not wearing shoes now',
            'What is she wearing now?',
            'We are wearing boots now',
            'We are not wearing sweaters now'
            'They are wearing sandals now',
            'They are not wearing suits now',
            'What are they wearing now?',
            'I am running now',
            'I am not running now',
            'You are running now',
            'You are not running now',
            'She is running now',
            'She is not running now',
            'He is running now',
            'He is not running now',
            'We are running now',
            'We are not running now',
            'They are running now',
            'They are not running now',
            'What are you doing?',
            'Where is he running now?',
            'I am writing a letter now',
            'I am not writing a letter now',
            'You are writing a letter now',
            'You are not writing a letter now',
            'She is writing a letter now',
            'She is not writing a letter now',
            'He is writing a letter now',
            'He is not writing a letter now',
            'We are writing a letter now',
            'We are not writing a letter now',
            'They are writing a letter now',
            'They are not writing a letter now',
            'Are they writing a letter now?',
            'Is he writing a letter now?',
            'Is she writing a letter now?',
            'Are you writing a letter now?',
            'I am sitting now',
            'I am not sitting now',
            'You are sitting now',
            'You are not sitting now',
            'He is sitting now',
            'He is not sitting now',
            'Is he sitting now?',
            'She is sitting now',
            'She is not sitting now',
            'Is she sitting now?',
            'We are sitting now',
            'We are not sitting now',
            'They are sitting now',
            'They are not sitting now',
            'Are they sitting now?',
            'I am washing my hair now',
            'I am not washing my hair now',
            'You are washing your hair now',
            'You are not washing your hair now',
            'He is washing his hair now',
            'He is not washing his hair now',
            'She is washing her hair now',
            'She is not washing her hair now',
            'Is she washing her hair now?',
            'Is he washing his hair now?',
            'We are washing our hair now',
            'We are not washing our hair now'
            'They are washing their hair now',
            'They are not washing their hair now',
            'The baby is crying',
            'The baby is not crying',
            'Is the baby crying?',
            'I am cooking dinner now',
            'I am not cooking dinner now',
            'You are cooking dinner now',
            'You are not cooking dinner now',
            'Are you cooking dinner now?',
            'He is cooking dinner now',
            'He is not cooking dinner now',
            'Is he cooking dinner now?',
            'She is cooking dinner now',
            'She is not cooking dinner now',
            'Is she cooking dinner now?',
            'We are cooking dinner now',
            'We are not cooking dinner now',
            'They are cooking dinner now',
            'They are not cooking dinner now',
            'Are they cooking dinner now?'
        ],
        'tis': [
            'There is a key in the door',
            'There is not a key in the door',
            'Is there a key in the door?'
            'There are three trees in the garden',
            'There are no trees in the garden',
            'Are there trees in the garden?'
            'There is no music that I hate',
            'Is there music that you hate?'
            'There are some great books which I want for Christmas',
            'There are three floors in the house',
            'Are there three floors in the house?',
            'There is not any food in the fridge',
            'There are so many stars in the sky tonight',
            'There is a new restaurant opening across the street',
            'There are four cups of coffee on the table',
            'There are some flowers on the table',
            'There are not any flowers on the table',
            'Are there any flowers on the table?',
            'There is a lot of fish in the pond',
            'There is not any fish in the pond',
            'Are there any of fish in the pond?',
            'There is a red roof on that house',
            'Is there a red roof on that house?',
            'There are a few children in the park',
            'There are not any a few children in the park',
            'Are there any children in the park?',
            'There is a dish on the shelf',
            'There is not any a dish on the shelf',
            'Is there a dish on the shelf?',
            'There are some potatoes in these boxes',
            'There are not any potatoes in these boxes',
            'Are there any potatoes in these boxes?',
            'There are a lot of books in the library',
            'Are there a lot of books in the library?',
            'There are not a lot of books in the library',
            'How many books are there in the library?',
            'There are two apples on the table',
            'How many apples are there on the table?',
            'There is not a boy in the street',
            'There is a boy in the street',
            'Is there an ATM near here?',
            'There is an ATM near here',
            'There will be a party tomorrow',
            'Will there be a party tomorrow?',
            'There will be no party tomorrow',
            'There were a lot of illnesses in the 14th century',
            'There were not a lot of illnesses in the 20th century',
            'Were there a lot of illnesses in the 14th century?',
            'There is a cafe next to the bank',
            'There is not any cafes next to the bank',
            'Is there a cafe next to the bank?',
            'Is there a table in the garden?',
            'There is a table in the garden',
            'There are not any tables in the garden',
            'There is not a bath in my flat',
            'There is a bath in my flat',
            'Is there a bath in your flat?',
            'Is there a train to Glasgow tonight?',
            'There is a train to Glasgow tonight',
            'There are not any trains to Glasgow tonight',
            'Is there somewhere to get coffee in the station?',
            'There are a lot of mountains in Switzerland',
            'There are not a lot of mountains in Switzerland',
            'Are there a lot of mountains in Switzerland?',
            'There are not many mosquitoes near the lake',
            'There are a lot of mosquitoes near the lake',
            'Are there a lot of mosquitoes near the lake?',
            'There is not any bread in the kitchen',
            'There is some bread in the kitchen',
            'Is there any bread in the kitchen?',
            'Is there a good clothes shop in this town?',
            'There are a few good clothes shop in this town',
            'There are not any good clothes shop in this town',
            'There is a police station nearby',
            'There are not any police stations nearby',
            'Are there any police stations nearby?',
            'There are no flowers in the hall',
            'There are some flowers in the hall',
            'Are there any flowers in the hall?',
            'There is a lot of traffic in Valencia',
            'There is not a lot of traffic in Valencia',
            'Is there a lot of traffic in Valencia?',
            'There is not much sugar',
            'Is there any sugar?',
            'There is enough sugar',
            'There is enough time to finish this task',
            'Is there enough time to finish this task?',
            'There is not enough time to finish this task',
            'There are a few bananas and a few apples in the fridge',
            'Are there any bananas and apples in the fridge?',
            'There are not any bananas and apples in the fridge',
            'There is only one way to solve this problem',
            'Is there only one way to solve this problem?',
            'There is not only one way to solve this problem',
            'There are not many tigers left in the world',
            'Are there any tigers left in the world?',
            'Are there any public buses in Los Angeles?',
            'There a few public buses in Los Angeles',
            'There are not any public buses in Los Angeles'
        ],
        'going_to': [
            'Jim is going to see his friends',
            'Jim is not going to see his friends',
            'Is Jim going to see his friends?',
            'I am going to call my friends',
            'I am not going to call my friends',
            'Are you going to call your friends?',
            'He is going to call his friends',
            'He is not going to call his friends',
            'Is he going to call his friends?',
            'She is going to call her friends',
            'She is not going to call her friends',
            'Is she going to call her friends?',
            'He is not going to cook',
            'He is going to cook',
            'Is he going to cook?',
            'He is not going to do housework',
            'She is going to do housework',
            'Is she going to do housework?',
            'We are going to go shopping',
            'Are you going to go shopping?',
            'We are not going to go shopping',
            'I am going to go shopping',
            'They are going to wash their hair',
            'They are not going to wash their hair',
            'Are they going to wash their hair?',
            'I am going to wash my hair',
            'I am not going to wash my hair',
            'You are going to wash your hair',
            'You are not going to wash your hair',
            'Are you going to wash your hair?',
            'He is going to wash his hair',
            'He is not going to wash his hair',
            'Is he going to wash his hair?',
            'We are going to wash our hair',
            'We are not going to wash our hair',
            'Are we going to wash our hair?',
            'They are not going to play computer games',
            'They are going to play computer games',
            'I am going to play computer games',
            'I am not going to play computer games',
            'You are going to play computer games',
            'You are not going to play computer games',
            'Are you going to play computer games?',
            'He is going to play computer games',
            'He is not going to play computer games',
            'Is he going to play computer games?',
            'She is going to play computer games',
            'She is not going to play computer games',
            'Is she going to play computer games?',
            'We are going to play computer games',
            'We are not going to play computer games',
            'They are not going to visit Jim',
            'They are going to visit Jim',
            'Are they going to visit Jim?',
            'I am going to visit Jim',
            'I am not going to visit Jim',
            'You are going to visit Jim',
            'You are not going to visit Jim',
            'Are you going to visit Jim?',
            'He is going to visit Jim',
            'He is not going to visit Jim',
            'Is he going to visit Jim?',
            'She is going to visit Jim',
            'She is not going to visit Jim',
            'Is she going to visit Jim?',
            'We are going to visit Jim',
            'We are not going to visit Jim',
            'I am going to read a book',
            'I am not going to read a book',
            'You are going to read a book',
            'You are not going to read a book',
            'Are you going to read a book?',
            'He is going to read a book',
            'He is not going to read a book',
            'Is he going to read a book?',
            'She is going to read a book',
            'She is not going to read a book',
            'Is she going to read a book?',
            'We are going to read a book',
            'We are not going to read a book',
            'They are going to read a book',
            'They are not going to read a book',
            'Are they going to read a book?',
            'I am going to be ill',
            'I am not going to be ill',
            'You are going to be ill',
            'You are not going to be ill',
            'Are you going to be ill?',
            'He is going to be ill',
            'He is not going to be ill',
            'Is he going to be ill?',
            'She is going to be ill',
            'She is not going to be ill',
            'Is she going to be ill?',
            'We are going to be ill',
            'We are not going to be ill',
            'They are going to be ill',
            'They are not going to be ill',
            'Are they going to be ill?',
            'It is not going to rain',
            'It is going to rain',
            'Is it going to rain?',
            'It is going to snow',
            'It is not going to snow',
            'Is it going to snow?'
        ]
    },
    'pre_select': ['Present Perfect vs Past Simple',
                   'PPC',
                   'PPC vs Past Simple'],
    'pre': {
        'pp_vs_ps': [
            'I have had 2 classes this week',
            'I had 2 classes last week',
            'She has not been at the office today',
            'She was not at the office yesterday',
            'I have not finished my work yet',
            'I did not finish my work on Monday',
            'We have recently opened 2 new offices in Moscow',
            'We opened 2 new offices in Moscow in January',
            'Have you ever been to Italy?',
            'When did you go to Spain?',
            'Who was with you in Italy?',
            'What did you see in Berlin?',
            'We have just arrived',
            'I have just broken a glass',
            'He has just come to the office',
            'She has not come to the office yet',
            'I have just watched a film',
            'Have you ever watched this film?',
            'Have you ever travelled by car?',
            'My grandparents only knew each other for a few months before they got married',
            'I have already been in London for three years',
            'We saw Julie last night',
            'He was a teacher before he became a musician',
            'When the boss walked into the room, we knew someone was going to be fired',
            'The children broke a window in the school last week',
            'He saw that film last year',
            'Lucy has broken her leg, so she can’t come skiing',
            'They were cold when they arrived home',
            'Jack broke his arm when he fell off a horse in 2005',
            'I have not found a solution to the problem yet',
            'When did you arrive?',
            'When did you break the glass?',
            'When did you go to the party?',
            'She has been a teacher for ten years, and she still enjoys it',
            'How long have you known Jill?',
            'I have never seen the sea before',
            'I have not finished the report yet',
            'I did not finish the report yesterday',
            'Have you finished the report yet?',
            'Did you finish the report last week?',
            'I think I have lost my keys',
            'I have just spoken to him by the phone',
            'I spoke to him by the phone yesterday',
            'He was here yesterday',
            'When I was in Spain, I met an old friend',
            'Have you ever been to Austria?',
            'Did you go to Austria last winter?',
            'Have you had breakfast today?',
            'When did you have breakfast?',
            'Have you had lunch today?',
            'When did you have lunch?',
            'I had lunch at 3',
            'I have not had lunch yet',
            'He has not had lunch yet',
            'I have recently written to him',
            'He did not write to me last month',
            'Have you read this book?',
            'I read this book 2 years ago',
            'I saw this film 3 months ago'
        ],
        'ppc': [
            'I have been smoking for 10 years',
            'He has been smoking for 5 years',
            'How long have you been smoking?',
            'She has been driving cars for 25 years',
            'How long has he been driving cars?',
            'I have been working for Apple for a month',
            'He has been working in our office for a few years',
            'How long has she been working for Microsoft?',
            'How long have they been working for this company?',
            'I have been learning English for all my life',
            'He has been learning English for 2 years',
            'How long have you been learning English?',
            'Have you been learning English long?',
            'The tap has been leaking since last week',
            'It has been snowing since last night',
            'The children have been studying for an hour',
            'John has been smoking since he was a teenager',
            'Andrea has been working in a bank since last April',
            'Mrs. Neville has been teaching French for 15 years',
            'Sue and Joe have been planning their vacation since last winter',
            'The mechanic has been working on my car since this morning',
            'How long has Ruth been waiting for Sara?',
            'Where has Annie been cooking all day?',
            'Why has he been walking to work all week?',
            'How long has it been raining?',
            'She has been taking piano lessons since she was a child',
            'They have been fishing since the sun rose',
            'He has been arguing with his father for an hour',
            'We have been living in the same apartment since we were children',
            'Alex has been sleeping since he came home from his business trip',
            'The students have been doing this exercise since they came to class',
            'Peter has been watching the hockey game since it began',
            'Dan and Luke have been playing tennis for two hours',
            'Bonnie has been taking vitamins since she got a very bad flu',
            'Dave has been walking to work since his car broke',
            'She has been dieting since her doctor told her to lose weight'
        ],
        'ppc_vs_ps': [
            'Have you bought your train ticket yet?',
            'What have the children been doing all this time?',
            'Julie has been learning to drive for six years',
            'Amanda has already had lunch, so she will meet us later',
            'How much coffee has she drunk this morning?',
            'Simon has written three books',
            'I have done everything I needed to do today!',
            'It has not rained all summer, so the garden is dead',
            'I have already read your book',
            'He has been reading my books for a month',
            'She has forgotten how to get to my house',
            'I have been working in the garden all day and I need a rest'
            'She has made three cakes',
            'He has been waking up early all this week',
            'We have always hated rush hour traffic',
            'Recently, I have been studying a lot',
            'We have been writing this book for months and months',
            'I have always loved chocolate',
            'I have wanted to go back to university for a long time',
            'I have watched seven films this week!',
            'I have not done the housework yet',
            'They have been studying very hard recently',
            'She has promised to help many times',
            'He has finally cleaned the kitchen',
            'She has written her essay and has sent it to her professor',
            'He has seen the film ‘The King’s Speech’ about six times',
            'We have already painted our living room',
            'She has been taking French lessons lately',
            'Lucy has already left',
            'How many times have you visited Scotland?',
            'I have been calling John for hours and hours and he has not answered',
            'I have been in London for three years',
            'We have known James for ages',
            'How much petrol has she bought?',
            'She has been eating chocolate all morning, so she feels sick',
            'I have been painting my house all day, but it’s not finished yet',
            'Julie has been at the office since 6 am'
        ]
    },
    'int_select': ['Passive Voice', 'Modal Verbs: advice'],
    'inter': {
        'passive': [
            '100 new houses are built in the city every year',
            '200 new houses were built in the city last year',
            '300 old houses have been demolished this year',
            'A new district will be built here next year',
            'Cars are always produced in this factory',
            'That shirt must be washed for tonight’s party',
            'The food is going to be prepared soon',
            'The food was prepared yesterday',
            'The food had been prepared before I came home',
            'The food will have been prepared when I come home'
            'Shoes are always made in that factory',
            'Shoes have been made in that factory since 1960',
            'These shoes were made last year',
            'Preparations had been finished by the time the guests arrived',
            'The visitors will be met at the airport by the delegation',
            'I have just been met at the airport by my friend',
            'He was met at the station in the morning',
            'I am going to be picked up from the airport by my sister',
            'Skis have been produced here since 1964',
            'German is also spoken at EU meetings',
            'The question must be looked into immediately',
            'I know that the question is being looked into now',
            'The newspaper is read to him every day',
            'Acupuncture was discovered by the Chinese thousands of years ago',
            'America was not discovered by Christopher Columbus',
            'Have you been given back the book yet?',
            'The cake is being eaten by the boy now',
            'I was promised a box of chocolates',
            'She was scared by a spider when she saw it',
            'My car is being washed now',
            'Her relatives were shown the new house on Friday last week',
            'I was introduced to Harry at the party last night'
        ],
        'mv_a': [
            'I think you should see a doctor about that',
            'I think you need to watch this film',
            'Maybe you should get some rest',
            'Why don\'t you get some rest?',
            'Maybe you ought to try it',
            'Maybe you ought to go to bed early tonight',
            'You really should make an appointment',
            'Why don\'t you call the doctor now?',
            'Why don\'t you call the doctor now and see if you go in tomorrow?',
            'I don\'t think you should go out now if you\'re not feeling well',
            'Why don\'t you think about it for a few days?',
            'What should we do about the cat?',
            'If you have an allergy, maybe we should think about finding the cat another home?',
            'I think you ought to take some pills',
            'You ought to complain about his behaviour',
            'If you feel like that, why don\'t you change your doctor?',
            'If you ask me, I would change my diet',
            'Why don\'t you eat more healthy food',
            'I think you should go to bed early every day',
            'You ought to buy some medicine'
        ]
    },
    'adv_select': ['All Tenses', 'Emphatic Constructions'],
    'adv': {
        'all_tenses': [
            'He did not forget to come',
            'I just remembered that I have not paid the rent yet',
            'He has been playing the bagpipes since six this morning',
            'When I first met him he was studying architecture',
            'He did not forget to come',
            'It has been raining for the last two hours so the game has been postponed',
            'When I saw him he was painting a picture of his wife',
            'The engine was running but nobody was in the car.',
            'Tom can’t have the newspaper now because his aunt is reading it.',
            'This shop is closing forever next Monday.',
            'Where are you going tonight?',
            'At 3 a.m. Jane woke up her husband and said that she thought that someone was '
            'trying to get into the house.',
            'When you see me next time I will be wearing my new sunglasses.',
            'Some time ago I read that our mayor wanted to go to Iceland',
            'She fell ill two days ago and since then she has not eaten anything',
            'Most people were at work when the fire started',
            'I saw him when he left the house',
            'I was just standing at the corner when he passed by',
            'They have been in Chicago for 20 years',
            'I saw a wonderful film in the cinema last night',
            'The sun rose at 6:38 yesterday morning',
            'The sun was shining when the climber reached Mount Everest',
            'I promise that I will not tell this secret to anyone',
            'They sometimes go to the movies',
            'I was tired yesterday because I had not slept well the night before',
            'Someone is listening to our conversation',
            'When I left the house this morning, it was already raining',
            'I think Bob is leaving for London now',
            'I am not wearing my watch because it is being fixed',
            'This has been an easy quiz so far',
            'They are living in an apartment right now because they can’t find a cheap house',
            'Everyone was sleeping when the earthquake hit the small town',
            'He has been living by himself since his divorce',
            'I was angry that I had made such a stupid mistake',
            'He quit his job a couple of years ago',
            'Our daughter has not graduated from the university yet',
            'They didn’t send any Christmas cards last year',
            'She goes to a doctor once a year for an examination',
            'They were talking about me when I interrupted their conversation',
            'Nothing much was happening when I got to the meeting',
            'My parents will be in New York two weeks from today',
            'I made two mistakes in the last quiz',
            'Unfortunately, our team did not win any games last year',
            'My family have bought some land in southern France recently',
            'They are building a summer house there at the moment',
            'Andy and Mary are going to a concert tomorrow night',
            'Jonathon watches the news on TV every day and it helps him with his English',
            'When I was driving home from work my car broke down.',
            'When he founded Microsoft, Bill Gates was only 20 years old.',
            'An accident happened near my house last night.',
            'They had been standing in the queue for over an hour when the manager told them '
            'that there were no more tickets.'
        ],
        'emph_str': [
            'It was Mike who took Sally to the party on Saturday',
            'It was Sally that Mike took to the party on',
            'It was on Saturday that Mike took Sally to the party',
            'What Mike did was to take Sally to the party.',
            'It was to the party that Mike took Sally on',
            'It was because of greed that he did it',
            'What the boys are doing is taking Sandy to the match',
            'The guy who told me about the new club was Zack',
            'The house where I used to live is near here',
            'The day when we left was the saddest day of my life',
            'The thing I most disliked about the movie was the scene in the graveyard',
            'The only thing we want is to celebrate the new year with the family',
            'The thing we will not do is repair goods bought in other shops',
            'The only thing we did not find was the key to the cellar',
            'This is where we need to get off',
            'That is what they told me',
            'Friendly she may be, but reliable she isn’t',
            'It was not what really bothered me',
            'What really bothered me was the total lack of any decent public transport',
            'What worries me the most is the lack of censorship',
            'One thing that scares me is the amount of money spent on weapons',
            'One thing that annoys me is the way the president talks',
            'One thing that drives me mad is the traffic in the city',
            'What bothers me is the lack of investment into art and culture',
            'What concerns me is the power judges have',
            'One thing that gives me hope for future is that I can speak English well',
            'What happened was I decided to research my roots',
            'What bothers me is the fact that he is not elected',
            'One thing that worries me is the amount of money wasted',
            'What has surprised me is the number of applications',
            'The thing that most annoys me is the way he talks to people'
        ]
    }
}
